// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zggklblpyaayrqdtliaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZ2tsYmxweWFheXJxZHRsaWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2OTg0NDgsImV4cCI6MjA1MDI3NDQ0OH0._0vz8XqenFldPNSNp4fQTmccq92zZPOkHCsiyV-CVVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);